name: Build

on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 30
    services:
      postgres:
        image: postgis/postgis:14-3.1-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        # Set health checks to wait until postgres has started
        options: --health-cmd "pg_isready -d test -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5 -it
        ports:
          - '5432:5432'
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test?connect_timeout=300
      DEBUG: "*"
      PGPASSFILE: ./.pgpass
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      - uses: iamsauravsharma/create-dotenv@v1.2.1
      - name: Build
        run: |
                echo 'localhost:5432:test:postgres:postgres' > ./.pgpass
                yarn install
                yarn prisma migrate reset --force
